<?php
/**
 * TL_ROOT/system/modules/subcolumns/languages/cs/default.php 
 * 
 * Contao extension: subcolumns 2.0.0 rc1 
 * Czech translation file 
 * 
 * Copyright : 2008-2012 Felix Pfeiffer : Neue Medien, 2005-2012 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['subcolumn'] = "Více sloupců";
$GLOBALS['TL_LANG']['CTE']['subcolumns']['0'] = "Více sloupců";
$GLOBALS['TL_LANG']['CTE']['subcolumns']['1'] = "<img src=\"system/modules/subcolumns/html/example_de.png\" alt=\"Příklad pro více sloupců\" style=\"float:right;\" />Více sloupců nabízí možnost přidat více sloupců do layoutu. Sloupce mohou být i vrstvené (kaskádové) sloupce.";
$GLOBALS['TL_LANG']['CTE']['colsetStart']['0'] = "Více sloupců - Start";
$GLOBALS['TL_LANG']['CTE']['colsetStart']['1'] = "Start definuje nastavení sloupců.<br />Pokud změníte počet sloupců nebo jejich šířku, automaticky se změní elementy propojené s tímto nastavením.<br />Pokud změníte počet sloupců - např. ze dvou na tři - bude přidán druhý element. Při změně ze tří na dva sloupce, bude poslední element smazán a obsah třetího sloupce se zobrazí pod nastavením.";
$GLOBALS['TL_LANG']['CTE']['colsetPart']['0'] = "Více sloupců - Část";
$GLOBALS['TL_LANG']['CTE']['colsetPart']['1'] = "V této části nemůžete měnit nastavení sloupce.<br /> DŮLEŽITÉ: POKUD VYMAŽETE TENTO ELEMENT, VYMAŽETE TAKÉ ELEMENTY V PROPOJENÉM NASTAVENÍ SLOUPCŮ!";
$GLOBALS['TL_LANG']['CTE']['colsetEnd']['0'] = "Více sloupců - Konec";
$GLOBALS['TL_LANG']['CTE']['colsetEnd']['1'] = "V této části nemůžete měnit nastavení sloupce.<br /> DŮLEŽITÉ: POKUD VYMAŽETE TENTO ELEMENT, VYMAŽETE TAKÉ ELEMENTY V PROPOJENÉM NASTAVENÍ SLOUPCŮ!";
$GLOBALS['TL_LANG']['MSC']['contentAfter'] = "<img src=\"system/modules/subcolumns/html/down.gif\" alt=\"Beispiel für Spaltensets\" style=\"float:left;\" />Place all content for the %s column after this element.";
$GLOBALS['TL_LANG']['MSC']['sc_first'] = "první";
$GLOBALS['TL_LANG']['MSC']['sc_second'] = "druhý";
$GLOBALS['TL_LANG']['MSC']['sc_third'] = "třetí";
$GLOBALS['TL_LANG']['MSC']['sc_fourth'] = "čtvrtý";
$GLOBALS['TL_LANG']['MSC']['sc_fifth'] = "pátý";
 
?>
