<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/cs/modules.php 
 * 
 * Contao extension: subcolumns 2.0.0 rc1 
 * Czech translation file 
 * 
 * Copyright : 2008-2012 Felix Pfeiffer : Neue Medien, 2005-2012 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['subcolumns']['0'] = "Nastavit sloupce";
$GLOBALS['TL_LANG']['FMD']['subcolumns']['1'] = "Nastavení je prováděno podobně jako rozložení stránky.";
 
?>
