<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/cs/tl_content.php 
 * 
 * Contao extension: subcolumns 2.0.0 rc1 
 * Czech translation file 
 * 
 * Copyright : 2008-2012 Felix Pfeiffer : Neue Medien, 2005-2012 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['sc_name']['0'] = "Jméno";
$GLOBALS['TL_LANG']['tl_content']['sc_name']['1'] = "Tento název se používá pro propojení celé částí Více sloupců dohromady.";
$GLOBALS['TL_LANG']['tl_content']['sc_gap']['0'] = "Mezera mezi sloupci";
$GLOBALS['TL_LANG']['tl_content']['sc_gap']['1'] = "Definuje prostor mezi dvěma sloupci v px. Výchozí hodnota je nastavena na 12px.";
$GLOBALS['TL_LANG']['tl_content']['sc_gapdefault']['0'] = "Vlastní mezera mezi sloupci";
$GLOBALS['TL_LANG']['tl_content']['sc_gapdefault']['1'] = "Chcete definovat vlastní mezeru mezi sloupci? Výchozí hodnota je nastavena na 12px.";
$GLOBALS['TL_LANG']['tl_content']['sc_type']['0'] = "Typ";
$GLOBALS['TL_LANG']['tl_content']['sc_type']['1'] = "Kolik sloupců a jaké šířky by měly být vytvořeny. Čísla udávají šířku v procentech: např. 25x75 => první sloupec 25%, druhý sloupec 75% v tomto kontejneru.";
$GLOBALS['TL_LANG']['tl_content']['sc_equalize']['0'] = "Stejné výšky";
$GLOBALS['TL_LANG']['tl_content']['sc_equalize']['1'] = "Tato možnost nastaví výšku všech sloupců na výšku nejdelšího sloupce. Příklad této funkce lze nalézt na webové stránce <a href=\"http://www.yaml.de/fileadmin/examples/06_layouts_advanced/equal_height_boxes.html\" onclick=\"window.open(this.href); return false;\" title=\"YAML-Framework\">YAML framework</a>.";
$GLOBALS['TL_LANG']['tl_content']['colset_legend'] = "Více sloupců - Nastavení";
$GLOBALS['TL_LANG']['tl_content']['colheight_legend'] = "Výška sloupce";
 
?>
