<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/cs/tl_form_field.php 
 * 
 * Contao extension: subcolumns 2.0.0 rc1 
 * Czech translation file 
 * 
 * Copyright : 2008-2012 Felix Pfeiffer : Neue Medien, 2005-2012 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FFL']['formcolstart']['0'] = "Více sloupců start";
$GLOBALS['TL_LANG']['FFL']['formcolstart']['1'] = "Otevření více sloupců";
$GLOBALS['TL_LANG']['FFL']['formcolpart']['0'] = "Více sloupců - část";
$GLOBALS['TL_LANG']['FFL']['formcolpart']['1'] = "Část mezi dvěma sloupci.";
$GLOBALS['TL_LANG']['FFL']['formcolend']['0'] = "Více sloupců - Konec";
$GLOBALS['TL_LANG']['FFL']['formcolend']['1'] = "Poslední část více sloupců.";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_type']['0'] = "Více sloupců";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_type']['1'] = "Vyberte typ více sloupců.";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_name']['0'] = "Název";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_name']['1'] = "Zadejte názve pro více sloupců. Pokud nezadáte název, Contao si vytvoří vlastní.";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_gapuse']['0'] = "Vlastní mezera mezi sloupci.";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_gapuse']['1'] = "Chcete definovat vlastní mezeru mezi sloupci? Výchozí hodnota je nastavena na 12px.";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_gap']['0'] = "Mezera";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_gap']['1'] = "Zadejte vlastní mezeru mezi sloupci v px. Výchozí hodnota je 12px.";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_equalize']['0'] = "Stejná výška sloupců";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_equalize']['1'] = "Zaškrtněte tuto možnost, aby se nastavila stejná výška sloupců.";
$GLOBALS['TL_LANG']['tl_form_field']['colsettings_legend'] = "Nastavení sloupců";
 
?>
