<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/cs/tl_module.php 
 * 
 * Contao extension: subcolumns 2.0.0 rc1 
 * Czech translation file 
 * 
 * Copyright : 2008-2012 Felix Pfeiffer : Neue Medien, 2005-2012 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['sc_modules']['0'] = "Vyberte moduly";
$GLOBALS['TL_LANG']['tl_module']['sc_modules']['1'] = "V případě, že je deaktivovaný Javasckript, uložte si provedené změny před změnou příkazu.";
$GLOBALS['TL_LANG']['tl_module']['sc_gap']['0'] = "Vlastní mezera";
$GLOBALS['TL_LANG']['tl_module']['sc_gap']['1'] = "Zadejte vlastní mezeru mezi sloupci v px. Výchozí hodnota je 12px.";
$GLOBALS['TL_LANG']['tl_module']['sc_gapdefault']['0'] = "Vlastní mezera";
$GLOBALS['TL_LANG']['tl_module']['sc_gapdefault']['1'] = "Chcete mít vlastní mezeru mezi dvěma sloupci? Výchozí hodnota je 12px.";
$GLOBALS['TL_LANG']['tl_module']['sc_type']['0'] = "Nastavení sloupce";
$GLOBALS['TL_LANG']['tl_module']['sc_type']['1'] = "Vyberte si typ pro více sloupců";
$GLOBALS['TL_LANG']['tl_module']['sc_equalize']['0'] = "Stejná výška";
$GLOBALS['TL_LANG']['tl_module']['sc_equalize']['1'] = "Zaškrtněte tuto možnost, aby se nastavila stejná výška sloupců.";
$GLOBALS['TL_LANG']['tl_module']['subcolumns_legend'] = "Nastavení sloupce";
$GLOBALS['TL_LANG']['tl_module']['subcolumns_settings_legend'] = "Nastavení sloupce";
$GLOBALS['TL_LANG']['tl_module']['module'] = "Modul";
$GLOBALS['TL_LANG']['tl_module']['column'] = "Sloupec";
 
?>
