<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/cs/tl_settings.php 
 * 
 * Contao extension: subcolumns 2.0.0 rc1 
 * Czech translation file 
 * 
 * Copyright : 2008-2012 Felix Pfeiffer : Neue Medien, 2005-2012 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['subcolumns_altcss']['0'] = "Použít originální YAML soubory";
$GLOBALS['TL_LANG']['tl_settings']['subcolumns_altcss']['1'] = "Pokud používáte YAML framework, měli byste zkontrolovat, jak subcolumns CE upravil css soubor, který drží pouze dodatečné šířky sloupců.";
$GLOBALS['TL_LANG']['tl_settings']['subcolumns_legend'] = "Více sloupců - Nastavení";
 
?>
