<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/it/default.php 
 * 
 * Contao extension: subcolumns 1.2.1 stable 
 * Italian translation file 
 * 
 * Copyright : 2008-2009 Felix Pfeiffer : Neue Medien, 2005-2009 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dan Nelu (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['subcolumn'] = "Insieme-Colonne";
$GLOBALS['TL_LANG']['CTE']['subcolumns']['0'] = "Insieme-Colonne";
$GLOBALS['TL_LANG']['CTE']['subcolumns']['1'] = "<img src=\"system/modules/Subcolumns/assets/example_de.png\" alt=\"Esempio di Insieme-Colonne\" style=\"float:right;\" />Insieme-Colonne offre la possibilità di aggiungere un insieme di colonne al tuo layout. Le colonne possono essere inserite a cascata.";
$GLOBALS['TL_LANG']['CTE']['colsetStart']['0'] = "Insieme-Colonne Inizio";
$GLOBALS['TL_LANG']['CTE']['colsetStart']['1'] = "L'elemento di inizio definisce l'insieme di colonne.<br />Se cambi il numero di colonne oppure la loro larghezza, allora queste operazioni saranno automaticamente aggiunte agli altri elementi collegati a questo insieme di colonne.<br />Se cambi il numero di colonne - i.e. da due a tre - un elemento parte-seconda sarà aggiunto. Quando si cambia da tre a due colonne, l'ultimo elemento, sarà cancellato e il contenuto della terza colonna sarà mostrato sotto l'insieme delle colonne.";
$GLOBALS['TL_LANG']['CTE']['colsetPart']['0'] = "Insieme-Colonne Elemento-parziale";
$GLOBALS['TL_LANG']['CTE']['colsetPart']['1'] = "Non puoi cambiare nessun'opzione dell'insieme delle colonne all'interno di questo content-element.<br /> IMPORTANTE: SE CANCELLI QUESTO CONTENT-ELEMENT, ANCHE GLI ALTRTI ELEMENTI COLLEGATI A QUESTO INSIEME COLONNE SARANNO CANCELLATI!!";
$GLOBALS['TL_LANG']['CTE']['colsetEnd']['0'] = "Insieme-Colonne Elemento-finale";
$GLOBALS['TL_LANG']['CTE']['colsetEnd']['1'] = "Non puoi cambiare nessun'opzione dell'insieme delle colonne all'interno di questo content-element.<br /> IMPORTANTE: SE CANCELLI QUESTO CONTENT-ELEMENT, ANCHE GLI ALTRTI ELEMENTI COLLEGATI A QUESTO INSIEME COLONNE SARANNO CANCELLATI!!";
$GLOBALS['TL_LANG']['MSC']['contentAfter'] = "Metti il contenuto della colonna %s dopo questo elemento.";
$GLOBALS['TL_LANG']['MSC']['sc_first'] = "primo";
$GLOBALS['TL_LANG']['MSC']['sc_second'] = "secondo";
$GLOBALS['TL_LANG']['MSC']['sc_third'] = "terzo";
$GLOBALS['TL_LANG']['MSC']['sc_fourth'] = "quarto";
$GLOBALS['TL_LANG']['MSC']['sc_fifth'] = "quinto";
 
?>
