<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/it/tl_content.php 
 * 
 * Contao extension: subcolumns 1.2.1 stable 
 * Italian translation file 
 * 
 * Copyright : 2008-2009 Felix Pfeiffer : Neue Medien, 2005-2009 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dan Nelu (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['sc_name']['0'] = "Nome Insieme-Colonne";
$GLOBALS['TL_LANG']['tl_content']['sc_name']['1'] = "Questo nome è utilizzato per collegare parti del insieme colonne.";
$GLOBALS['TL_LANG']['tl_content']['sc_gap']['0'] = "Spazio tra le colonne";
$GLOBALS['TL_LANG']['tl_content']['sc_gap']['1'] = "Lo spazio tra le colonne definisce lo spazio tra due colonne espresso in pixel. Il valore preimpostato è di 12px.";
$GLOBALS['TL_LANG']['tl_content']['sc_gapdefault']['0'] = "Usa lo spazio tra le colonne";
$GLOBALS['TL_LANG']['tl_content']['sc_gapdefault']['1'] = "Vuoi usare uno spazio tra le colonne?";
$GLOBALS['TL_LANG']['tl_content']['sc_type']['0'] = "Tipo Insieme-Colonne";
$GLOBALS['TL_LANG']['tl_content']['sc_type']['1'] = "Quante colonne e di che dimensione vuoi creare?<br />I numeri danno la larghezza in percentuale: 25x75 => prima colonna 25%, la seconda colonna 75% del container genitore.";
$GLOBALS['TL_LANG']['tl_content']['sc_equalize']['0'] = "Altezze uguali";
$GLOBALS['TL_LANG']['tl_content']['sc_equalize']['1'] = "Quest'opzione fissa tutte le colonne in un insieme con l'altezza uguale a quella della colonna più alta. In tal modo puoi usare le immagini di background o bordo.<br />Puoi trovare un esmpio a questa pagina web<a href=\"http://www.yaml.de/fileadmin/examples/06_layouts_advanced/equal_height_boxes.html\" onclick=\"window.open(this.href); return false;\" title=\"YAML-Framework\">YAML-framework</a>.";
$GLOBALS['TL_LANG']['tl_content']['colset_legend'] = "Impostazioni Insieme Colonne";
$GLOBALS['TL_LANG']['tl_content']['colheight_legend'] = "Altezza colonn";
 
?>
