<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/it/tl_form_field.php 
 * 
 * Contao extension: subcolumns 1.2.1 stable 
 * Italian translation file 
 * 
 * Copyright : 2008-2009 Felix Pfeiffer : Neue Medien, 2005-2009 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dan Nelu (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FFL']['formcolstart']['0'] = "Inizio Insieme Colonna";
$GLOBALS['TL_LANG']['FFL']['formcolstart']['1'] = "L'elemento di apertura di un insieme di colonne";
$GLOBALS['TL_LANG']['FFL']['formcolpart']['0'] = "Elemento parziale di un insieme di colonne";
$GLOBALS['TL_LANG']['FFL']['formcolpart']['1'] = "L'elemento tra due colonne.";
$GLOBALS['TL_LANG']['FFL']['formcolend']['0'] = "Fine elemento Insieme di colonne";
$GLOBALS['TL_LANG']['FFL']['formcolend']['1'] = "L'ultimo elemento di un insieme di colonne";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_type']['0'] = "Insieme di colonne";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_type']['1'] = "Seleziona il tipo dell'insieme colonne.";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_name']['0'] = "Nome";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_name']['1'] = "Inserisci un nome per l'insieme delle colonne. Se non inserisci nessun nome, contao ne inserirà uno da solo.";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_gapuse']['0'] = "Usa uno spazio";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_gapuse']['1'] = "Vuoi usare uno spazio tra due colonne?";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_gap']['0'] = "Spazio";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_gap']['1'] = "Inserisci lo spazio tra due colonne in pixel. Il valore standard è di 12px.";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_equalize']['0'] = "Altezze uguali";
$GLOBALS['TL_LANG']['tl_form_field']['fsc_equalize']['1'] = "Spunti questo riquadro per impostare altezze uguali per questo insieme di colonne.";
$GLOBALS['TL_LANG']['tl_form_field']['colsettings_legend'] = "Impostazioni colonne.";
 
?>
