<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/it/tl_module.php 
 * 
 * Contao extension: subcolumns 1.2.1 stable 
 * Italian translation file 
 * 
 * Copyright : 2008-2009 Felix Pfeiffer : Neue Medien, 2005-2009 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dan Nelu (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['sc_modules']['0'] = "Seleziona moduli";
$GLOBALS['TL_LANG']['tl_module']['sc_modules']['1'] = "Se javascript non è attivato, salva i cambiamenti prima di cambiare l'ordine.";
$GLOBALS['TL_LANG']['tl_module']['sc_gap']['0'] = "Spazio";
$GLOBALS['TL_LANG']['tl_module']['sc_gap']['1'] = "Inserisci lo spazio tra due colonne in pixel. Il valore preimpostato è di 12px.";
$GLOBALS['TL_LANG']['tl_module']['sc_gapdefault']['0'] = "Spazio definito dall'utente";
$GLOBALS['TL_LANG']['tl_module']['sc_gapdefault']['1'] = "Vuoi usare uno spazio tra due colonne?";
$GLOBALS['TL_LANG']['tl_module']['sc_type']['0'] = "Insieme colonne";
$GLOBALS['TL_LANG']['tl_module']['sc_type']['1'] = "Selezioni il tipo di insieme colonne";
$GLOBALS['TL_LANG']['tl_module']['sc_equalize']['0'] = "Altezze uguali";
$GLOBALS['TL_LANG']['tl_module']['sc_equalize']['1'] = "Spunti questo riquadro per impostare altezze uaguali per questo insieme di colonne.";
$GLOBALS['TL_LANG']['tl_module']['subcolumns_legend'] = "Insiem colonne";
$GLOBALS['TL_LANG']['tl_module']['subcolumns_settings_legend'] = "Impostazioni insieme colonn";
$GLOBALS['TL_LANG']['tl_module']['module'] = "Modulo";
$GLOBALS['TL_LANG']['tl_module']['column'] = "Colonna";
 
?>
