<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/it/tl_settings.php 
 * 
 * Contao extension: subcolumns 1.2.1 stable 
 * Italian translation file 
 * 
 * Copyright : 2008-2009 Felix Pfeiffer : Neue Medien, 2005-2009 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dan Nelu (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['subcolumns_altcss']['0'] = "Usa file YAML originali";
$GLOBALS['TL_LANG']['tl_settings']['subcolumns_altcss']['1'] = "Se usi un framework YAML, dovresti verificare quest'opzione, perché le sotto colonne CE caricano un file css modificato che contiene in più soltanto le larghezze delle colonne.";
$GLOBALS['TL_LANG']['tl_settings']['subcolumns_legend'] = "Impostazioni Insieme colonne";
 
?>
