<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/ru/tl_content.php 
 * 
 * TYPOlight extension: subcolumns 1.1.1 stable 
 * Russian translation file 
 * 
 * Copyright : 2008-2009 Felix Pfeiffer, 2005-2009 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['sc_name']['0'] = "Имя набора колонок";
$GLOBALS['TL_LANG']['tl_content']['sc_name']['1'] = "Это имя используется для связи частей вместе.";
$GLOBALS['TL_LANG']['tl_content']['sc_gap']['0'] = "Промежуток";
$GLOBALS['TL_LANG']['tl_content']['sc_gap']['1'] = "Промежуток определяет пространство между двумя колонками в пикселях. По умолчанию установлено 12 пикс.";
$GLOBALS['TL_LANG']['tl_content']['sc_type']['0'] = "Тип набора колонок";
$GLOBALS['TL_LANG']['tl_content']['sc_type']['1'] = "Сколько колонок и какой ширины должно быть создано?<br />Цифры ширины в процентах - 25x75 означает, что:<br />Первая колонка 25%, вторая колонка 75% ширины от родительского контейнера.";
$GLOBALS['TL_LANG']['tl_content']['sc_equalize']['0'] = "равных высот";
$GLOBALS['TL_LANG']['tl_content']['sc_equalize']['1'] = "Этот параметр устанавливает все колонки по высоте самой длинной. Это позволит использовать фоновые изображения и границы. <br />Пример для этой функции можно найти на веб-странице <a href=\"http://www.yaml.de/fileadmin/examples/06_layouts_advanced/equal_height_boxes.html\" onclick=\"window.open(this.href); return false;\" title=\"YAML-Framework\">YAML-framework</a>.";
$GLOBALS['TL_LANG']['tl_content']['colset_legend'] = "Настройки набора колонок";
$GLOBALS['TL_LANG']['tl_content']['colheight_legend'] = "Высота колонки";
 
?>
