<?php
/**
 * TL_ROOT/system/modules/Subcolumns/languages/ru/tl_settings.php 
 * 
 * TYPOlight extension: subcolumns 1.1.1 stable 
 * Russian translation file 
 * 
 * Copyright : 2008-2009 Felix Pfeiffer, 2005-2009 Dirk Jesse www.yaml.de 
 * License   : CC-A 2.0 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['subcolumns_altcss']['0'] = "Использовать оригинальные YAML файлы";
$GLOBALS['TL_LANG']['tl_settings']['subcolumns_altcss']['1'] = "Если вы используете фреймворк YAML, вы должны проверить эту опцию, как subcolumns CE редактируемого CSS-файла, который содержит только дополнительную ширину столбца.";
$GLOBALS['TL_LANG']['tl_settings']['subcolumns_legend'] = "Настройки набора колонок";
 
?>
